# coding=utf-8

#各个控件的id

WXID_BTN_SELECTED_DIR = 100
WXID_BTN_RUN = 101
WXID_RADIO_ENCODE_UTF8 = 102
WXID_RADIO_ENCODE_GBK = 103

#文字部分

STRINGS_NAME = u"Ozg WxApp"
STRINGS_STATIC_TEXT1 = u"需要处理的文件:"
STRINGS_STATIC_TEXT2 = u"待处理的文件夹:"
STRINGS_STATIC_TEXT3 = u"选择编码:"
STRINGS_TEXT_FILES_FILTER = u".h;.cpp;.plist"
STRINGS_BTN_SELECTED_DIR_TEXT = u"选择文件夹"
STRINGS_SELECTED_DIR_TEXT = u"选择文件夹"
STRINGS_ENCODE_UTF8_TEXT = u"UTF-8"
STRINGS_ENCODE_GBK_TEXT = u"GBK"
STRINGS_ENCODE_RADIO = u"file_encode"
STRINGS_BTN_RUN = u"执行"
STRINGS_DIALOG_TITLE = u"Ozg Notice"
STRINGS_DIALOG_MSG1 = u"执行本操作前请先备份文件"
STRINGS_DIALOG_MSG2 = u"需要处理的文件不能为空"
STRINGS_DIALOG_MSG3 = u"待处理的文件夹不能为空"
STRINGS_DIALOG_MSG4 = u"完成操作"
STRINGS_RUNNING_MSG = u"Complete processing"
